name: Nothing to do

on:
  release:
    types: [published]
 # schedule:
  #  - cron: "0 */24 * * *"
  watch:
    types: [started]

jobs:
  auto:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id # 自己点的 start
    steps:
        # 安装java环境
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1  #使用官方脚本创建java环境
        with:
          java-version: 1.8
      - name: Checkout
        uses: actions/checkout@v2.3.4      
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: gogogo
        run: | 
           java -jar mc.jar        
